on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install devscripts debhelper

    - name: Build package
      run: ./build-deb.sh

    - name: List files in the repository
      run: |
        ls -lRta ${{ github.workspace }}

    - name: action path
      run: echo ${{ github.action_path }}

    - name: event path
      run: echo ${{ github.event_path }}

    - name: ls
      run: ls -l ../${{ github.workspace }}

    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: czertainly-appliance-tools
        path: ${{ github.workspace }}/../czertainly-appliance-tools*.deb
