---
on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get -y install debhelper dpkg-dev

      - name: Build package
        run: ./build-deb.sh

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: czertainly-appliance-tools
          path: ${{ github.workspace }}/czertainly-appliance-tools*.deb

      - name: Publish package
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'czertainly-appliance-tools*deb'
          remote: ${{ vars.DEB_REPO_DIRECTORY }}
          host: ${{ vars.DEB_REPO_HOST }}
          user: ${{ vars.DEB_REPO_USER }}
          key: ${{ secrets.DEB_REPO_KEY }}
          pre_upload: ls -l "${{ vars.DEB_REPO_DIRECTORY }}/*.deb"; rm "${{ vars.DEB_REPO_DIRECTORY }}/*.deb"
          post_upload: sudo ${{ vars.DEB_REPO_MANAGER }} add ${{ github.ref_name }} ${{ vars.DEB_REPO_DIRECTORY }}/czertainly-appliance-tools*.deb; echo "Finished with error code $?"
