on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Install build dependencies
    #   run: sudo apt-get update && sudo apt-get -y install debhelper dpkg-dev

    # - name: Build package
    #   run: ./build-deb.sh

    # - name: Upload package artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: czertainly-appliance-tools
    #     path: ${{ github.workspace }}/czertainly-appliance-tools*.deb


    - run: echo ${{ secrets.DEB_REPO_HOST }}
    - run: echo ${{ env.DEB_REPO_HOST }}
    - run: echo ${{ env.DEB_REPO_USER }}

    - name: Publish package
      uses: mdallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: 'czertainly-appliance-tools*deb'
        remote: '~/'
        host: ${{ env.DEB_REPO_HOST }}
        user: ${{ env.DEB_REPO_USER }}
        key: ${{ secrets.DEB_REPO_KEY }}
        pre_upload: echo "This will be executed before the upload!"
        post_upload: echo "This will be executed after the upload!"
