on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install debhelper dpkg-dev

    - name: Build package
      run: ./build-deb.sh

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: czertainly-appliance-tools
        path: ${{ github.workspace }}/czertainly-appliance-tools*.deb
