---
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Show git status
        run: git status

      - name: Show git urls
        run: git config --get remote.origin.url ; git submodule foreach -q 'echo $(git config --get remote.origin.url)'

      - name: Verify submodules
        run: ./check-submodules
