---
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show git status
        run: git status

      - name: Verify submodules
        run: ./check-submodules
